blog/urls.py
from django.urls import path, include

from blog.views import AllBlogs, DetailBlog

app_name = 'blog'

urlpatterns = [
    path('', AllBlogs.as_view(), name='all_blogs'),
    path('<int:pk>/', DetailBlog.as_view(), name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from portfolio import views
from portfolio.views import HomeView, ContactUs, AddBook, AddPublisher, DetailBooks, AllBooks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactUs.as_view(), name='contact'),
    path('addpublisher/', AddPublisher.as_view(), name='addpublisher'),
    path('addbook/', AddBook.as_view(), name='addbook'),
    path('blog/', include('blog.urls')),
    path('all_books/', AllBooks.as_view(), name="all_books"),
    path('<int:pk>/', DetailBooks.as_view(), name='detailbooks'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models
from django.urls import reverse_lazy, reverse
from phonenumber_field.modelfields import PhoneNumberField


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(max_length=150, null=False, blank=False)
    phone = PhoneNumberField(null=False, blank=False)
    message = models.TextField(blank=False)

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    country = models.CharField(max_length=50)
    address = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    year = models.CharField(max_length=4, null=False, blank=False)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

portfolio/forms.py
from django import forms
from .models import Contact, Book, Publisher
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Row, Column, Submit, Layout, ButtonHolder, HTML


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('name'),
                Column('email'),
            ),
            Row(
                Column('phone'),
            ),
            Row(
                Column('message'),
            ),
            Row(
                Submit('submit', 'Submit', css_class="btn btn-primary"),
            ),
        )


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('title'),
                Column('year'),
            ),
            Row(
                Column('description'),
            ),
            Row(
                Column('publisher'),
            ),
            Row(
                HTML("""<a class="classes-for-styling" href="{% url 'addpublisher' %}">Add a new Publisher</a>"""),
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class="btn btn-primary"),
            ),
        )


class AddPublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('name'),
                Column('country'),
            ),
            Row(
                Column('address'),
            ),
            Row(
                Submit('submit', 'Submit', css_class="btn btn-primary"),
            ),
        )

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.views.generic import DetailView, ListView


# def all_blogs(request):
#     blogs = Blog.objects.order_by('-date')
#     return render(request, 'blog/all_blogs.html', {'blogs': blogs})
#
#
# def detail(request, blog_id):
#     blog = get_object_or_404(Blog, pk=blog_id)
#     return render(request, 'blog/detail.html', {'blog': blog})


class AllBlogs(ListView):
    objects = Blog.objects.all()
    template_name = 'blog/all_blogs.html'
    model = Blog
    context_object_name = 'blogs'


class DetailBlog(DetailView):
    template_name = 'blog/detail.html'
    model = Blog

portfolio/views.py
from django.contrib import messages
from django.urls import reverse_lazy

from .forms import ContactForm, AddBookForm, AddPublisherForm
from .models import Project, Book

from django.views.generic import ListView, FormView, DetailView
from django.shortcuts import render, redirect


# def home(request):
#     projects = Project.objects.all()
#     return render(request, 'portfolio/home.html', {'projects': projects})


class HomeView(ListView):
    template_name = 'portfolio/home.html'
    model = Project
    context_object_name = 'projects'


class ContactUs(FormView):
    form_class = ContactForm
    template_name = "portfolio/contact.html"
    success_url = reverse_lazy('contact')

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.INFO, 'Thank You for Contacting us')
        return super().form_valid(form)


class AddPublisher(FormView):
    form_class = AddPublisherForm
    template_name = "portfolio/publisher.html"
    success_url = reverse_lazy('addbook')

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.INFO, 'New Author Added')
        return super().form_valid(form)


class AddBook(FormView):
    form_class = AddBookForm
    template_name = "portfolio/book.html"
    success_url = reverse_lazy('addbook')

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.INFO, 'New book Added')
        return super().form_valid(form)


class DetailBooks(DetailView):
    template_name = 'portfolio/book_detail.html'
    model = Book


class AllBooks(ListView):
    objects = Book.objects.all()
    template_name = 'portfolio/all_books.html'
    model = Book
    context_object_name = 'books'

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Abd Alhameed has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}" id="blogt">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'jS M Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'jS M Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/all_books.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

    <div class="form-group col-md-8">
        <h1 class="display-4">Books Added:</h1>
    </div>

    {% for book in books %}

        <div class="col-md-10">
            <a href="{% url 'detailbooks' book.id %}">
                <h2>{{ book.title }}</h2>
            </a>
            <h6 class="text-muted">{{ book.year }}</h6>
            <h4>{{ book.publisher }}</h4>
            <br><br>
        </div>



    {% endfor %}
    <div class="col-md-10">
        <a class="btn btn-primary" href="{% url 'addbook' %}">Add a new Book</a>
    </div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <title>Abd Alhameed Sarayji</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" >
        <span>Abd Alhameed</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li>
            <a role="button" href="{% url 'contact' %}" class="nav-link">Contact Me</a>
             </li>
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/Abd ALhameed Sarayji CV.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/abd-alhamed-saraijy-1a1a96109/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://behance.net/abeedo" target="_blank">Behance</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'all_books' %}" target="_blank">Books</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/book.html
{% extends 'portfolio/base.html' %}
{% block content %}
{%  load static %}

{% load crispy_forms_tags  %}

 {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
 {% endif %}

 <div class="form-group col-md-8" >
        <h1 class="display-4 ">Add a new book</h1>
        </div>


            {% crispy form %}


{% endblock %}

portfolio/templates/portfolio/book_detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5">{{ book.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ book.description }}</h5>

<h5 class="text-center text-muted mb-5">{{ book.year }}</h5>

<h5 class="text-center text-muted mb-5">{{ book.publisher }}</h5>

{% endblock %}

portfolio/templates/portfolio/contact.html
{% extends 'portfolio/base.html' %}
{% block content %}
{%  load static %}

{% load crispy_forms_tags  %}

 {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
 {% endif %}

        <div class="form-group col-md-8" >
        <h1 class="display-4">Contact Us Through Email:</h1>
        </div>

        {% crispy form %}



{#        <form method="post">#}
{##}
{#            {% csrf_token %}#}
{##}
{#                {{form|crispy}}#}
{#            <div class="form-row">#}
{#                <div class="form-group col-md-6" >#}
{#                {{ form.name|as_crispy_field }}#}
{#                </div>#}
{##}
{#                <div class="form-group col-md-6" >#}
{#                {{ form.email|as_crispy_field }}#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="form-row">#}
{#                <div class="form-group col-md-12 " >#}
{#                {{ form.phone|as_crispy_field }}#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="form-row">#}
{#                <div class="form-group col-md-12 " >#}
{#                {{ form.message|as_crispy_field }}#}
{#                </div>#}
{#            </div>#}
{#                <button class="btn btn-primary" type="submit" value="Save" >Submit</button>#}
{##}
{##}
{#        </form>#}



{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}

    {%  load static %}

    <div class="row justify-content-center my-3">
      <div class="col-5">
        <img src="{% static 'portfolio/myphoto.jpg' %}" class="img-fluid">
     </div>
    </div>

    <div class="row justify-content-center mb-3">
      <div class="col-md-9 text-center">
        <h1 id="hometext">Abd Alhameed Sarayji</h1> <h2> Video Production Specialist - Programmer</h2>
        </div>
    </div>

    <h2 class="mt-5" id="portfolio">Portfolio</h2>
    <hr>
    <div class="row">
    {% for project in projects %}
        <div class="col-lg-4 col-md-6">
         {% if project.url %}
    <a href="{{ project.url }}" target="_blank">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2" >
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}

portfolio/templates/portfolio/publisher.html
{% extends 'portfolio/base.html' %}
{% block content %}
{%  load static %}

{% load crispy_forms_tags  %}

 {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
 {% endif %}

 <div class="form-group col-md-8" >
        <h1 class="display-4">Add a new Publisher:</h1>
        </div>


            {% crispy form %}


{% endblock %}